# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: \.(pkl|svg)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: \.(pkl|svg)$

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # - repo: https://github.com/google/yapf
  #   rev: v0.32.0
  #   hooks:
  #     - id: yapf
  #       name: "yapf"
  #       args: [-i, --style, .style.yapf]

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  #   rev: v1.0.1
  #   hooks:
  #     - id: rst-linter
  #       exclude: .*/doc/.*

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
